### ISSUE TITLE
New Extensions

### ISSUE THREAD

**Issue by hschneider** [neutralinojs-community/awesome-neutralino#1]
There are 2 new extensions, you might want to add:

https://github.com/hschneider/neutralino-ext-python
https://github.com/hschneider/neutralino-ext-bun

ThanX!

**Comment by shalithasuranga** [comment]
Hello. Thanks so much for posting nice extensions :) If possible, could you please send a PR for this repo by adding these items under a new title :tada:

**Comment by hschneider** [comment]
Done - thanks! :-)
